#!/usr/bin/env python3
"""Generate the derived geography VIEWS for The Unnecessary.

Standard library only. No third-party imports, no pip installs. This is a pure
view generator (entity-spec.md sections 4-5: derive, never store): it reads the
geography entity tree through scripts/entity_graph.py and WRITES three generated
documents into docs/20-canon/world/_generated/. None of these files is canon and
none is hand-edited -- each opens with a DO NOT EDIT banner and is overwritten on
every run. Re-run this after any geography change.

Outputs (one file each, all derived by walking the tree):

  street-network.md   a Mermaid map of the street NETWORK -- intersections as
                      nodes, segments as labelled edges between them, streets and
                      their `connects`, and every `addressed-to` building hung off
                      the network -- plus a plain-text edge listing.
  containment-tree.md the CONTAINMENT tree (folder/`parent` walk): the city at the
                      root, districts, buildings, rooms, objects nested beneath,
                      as an indented outline AND a Mermaid flowchart.
  street-index.md     "what's ON each street": per street, its segments, the
                      intersections it meets, and the addresses that reference it.

The content is deterministic (sorted, no timestamps) so re-running produces a
clean git diff only when the world actually changed.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import entity_graph as eg


OUTPUT_DIR = os.path.join(eg.REPO_ROOT, "docs", "20-canon", "world", "_generated")

GENERATOR = "scripts/build-geo-map.py"

# Front-matter targets that genuinely resolve (link/metadata validators check
# these): related is document-relative from _generated/, source_documents is
# repository-root-relative.
RELATED = "../index.md"
SOURCE_DOC = "docs/00-governance/entity-spec.md"

BANNER_COMMENT = (
    "<!-- DO NOT EDIT - generated by " + GENERATOR + ". "
    "This file is overwritten on every run; edit the entity files instead. -->"
)


def _safe(text):
    """Defang free text for a Markdown body: never emit a `](` link sequence."""
    return str(text).replace("](", "] (")


def _mm(text):
    """Sanitize a label for a Mermaid node/edge: strip glyphs that break it."""
    out = str(text)
    for bad in '[](){}"|<>':
        out = out.replace(bad, " ")
    out = out.replace("\n", " ").replace("\\", " ")
    return " ".join(out.split())


def _front_matter(title, summary):
    return "\n".join([
        "---",
        'title: "' + title + '"',
        'document_type: "generated-view"',
        'status: "generated"',
        'authority: "derived"',
        'summary: "' + summary + '"',
        "tags:",
        "  - world",
        "  - geography",
        "  - generated",
        "  - derived-view",
        "related:",
        '  - "' + RELATED + '"',
        "source_documents:",
        '  - "' + SOURCE_DOC + '"',
        "---",
        "",
    ])


def _banner_body(headline):
    return "\n".join([
        BANNER_COMMENT,
        "",
        "> **DO NOT EDIT - generated.** " + headline + " Produced by `"
        + GENERATOR + "` by walking the geography entity tree. Any hand edit is "
        "lost on the next run; change the underlying entity files instead.",
        "",
    ])


def _label(entity):
    return entity.title or entity.entity_id


def _type(entity):
    return entity.entity_type or "entity"


# ---------------------------------------------------------------------------
# View 1: the street network map.
# ---------------------------------------------------------------------------


def _intersections(graph):
    return sorted(
        (e for e in graph.entities.values() if e.entity_type == "intersection"),
        key=lambda e: e.key,
    )


def _connected_intersections(graph, street_key):
    """Intersection keys joined to a street by a `connects` edge on either end."""
    found = set()
    street = graph.entities.get(street_key)
    for inter in _intersections(graph):
        for edge in inter.edges:
            if edge.relation == "connects" and graph.resolve(edge.target) == street_key:
                found.add(inter.key)
    if street is not None:
        for edge in street.edges:
            if edge.relation == "connects":
                target = graph.resolve(edge.target)
                if target and graph.entities.get(target) and \
                        graph.entities[target].entity_type == "intersection":
                    found.add(target)
    return sorted(found)


def build_street_network(graph):
    node_id = {}

    def nid(key):
        if key not in node_id:
            node_id[key] = "n" + str(len(node_id))
        return node_id[key]

    lines = ["```mermaid", "flowchart LR"]
    edge_lines = []          # rendered mermaid edges
    listing = []             # plain-text edge listing (renders even without mermaid)

    intersections = _intersections(graph)
    streets = sorted(graph.streets(), key=lambda e: e.key)
    segments = sorted(graph.segments(), key=lambda e: e.key)

    # Nodes: intersections (rounded), streets (subroutine), addressed buildings.
    for inter in intersections:
        lines.append("  " + nid(inter.key) + '(["' + _mm(_label(inter))
                     + '"]):::intersection')
    for street in streets:
        lines.append("  " + nid(street.key) + '[["' + _mm(_label(street))
                     + '"]]:::street')

    # Segment edges, labelled with their single-source length.
    for seg in segments:
        a = graph.resolve(seg.seg_from)
        b = graph.resolve(seg.seg_to)
        if a is None or b is None:
            listing.append("- segment `" + _safe(seg.entity_id)
                           + "` has an unresolved endpoint; not drawn")
            continue
        length = (" (" + str(seg.length_m) + " m)") if isinstance(
            seg.length_m, (int, float)) else ""
        label = _mm(_label(seg) + length)
        edge_lines.append("  " + nid(a) + ' ---|"' + label + '"| ' + nid(b))
        listing.append("- `" + _safe(a.split("/")[-1]) + "` --["
                       + _safe(seg.entity_id) + _safe(length) + "]-- `"
                       + _safe(b.split("/")[-1]) + "`")

    # Street <-> intersection `connects` edges.
    drawn_connects = set()
    for street in streets:
        for inter_key in _connected_intersections(graph, street.key):
            pair = tuple(sorted((street.key, inter_key)))
            if pair in drawn_connects:
                continue
            drawn_connects.add(pair)
            edge_lines.append("  " + nid(inter_key) + " --- " + nid(street.key))
            listing.append("- `" + _safe(inter_key.split("/")[-1])
                           + "` connects street `" + _safe(street.entity_id) + "`")

    # Addressed buildings hung off the network by their `addressed-to` edge.
    for entity in sorted(graph.entities.values(), key=lambda e: e.key):
        for edge in entity.edges:
            if edge.relation != "addressed-to":
                continue
            res = graph.resolve_address(edge.payload or {})
            anchor_key = res.segment.key if res.resolved else graph.resolve(edge.target)
            lines.append("  " + nid(entity.key) + '["' + _mm(_label(entity))
                         + '"]:::building')
            if anchor_key is not None:
                edge_lines.append("  " + nid(entity.key) + " -.-> " + nid(anchor_key))
            street_name = res.street if res.street else edge.target
            listing.append("- building `" + _safe(entity.entity_id)
                           + "` addressed to `" + _safe(street_name) + "`")

    lines.extend(edge_lines)
    lines.append("  classDef intersection fill:#fde68a,stroke:#b45309,color:#1c1917;")
    lines.append("  classDef street fill:#bfdbfe,stroke:#1d4ed8,color:#1c1917;")
    lines.append("  classDef building fill:#e5e7eb,stroke:#374151,color:#1c1917;")
    lines.append("```")

    summary = (str(len(intersections)) + " intersection(s), " + str(len(streets))
               + " street(s), " + str(len(segments)) + " segment(s).")

    body = [
        _front_matter(
            "Geography -- Street Network (generated)",
            "Generated Mermaid map of the street network derived from the "
            "geography entity tree: intersections, segments, streets, and "
            "addressed buildings."),
        _banner_body("A map of the street network."),
        "# Street Network (generated)\n",
        summary + "\n",
        "## Map\n",
        "\n".join(lines),
        "",
        "## Edges\n",
        ("\n".join(listing) if listing
         else "_No network edges yet: the tree names a corner and a street but "
              "no segments or addresses._"),
        "",
    ]
    return "\n".join(body) + "\n"


# ---------------------------------------------------------------------------
# View 2: the containment tree.
# ---------------------------------------------------------------------------


def _roots(graph):
    return sorted(
        e.key for e in graph.entities.values()
        if e.parent_key is None
    )


def build_containment_tree(graph):
    outline = []
    mermaid = ["```mermaid", "flowchart TD"]
    node_id = {}

    def nid(key):
        if key not in node_id:
            node_id[key] = "c" + str(len(node_id))
        return node_id[key]

    def walk(key, depth):
        entity = graph.entities[key]
        outline.append("  " * depth + "- `" + _safe(entity.entity_id) + "` ["
                       + _safe(_type(entity)) + "] -- " + _safe(_label(entity)))
        mermaid.append("  " + nid(key) + '["' + _mm(_label(entity)) + " ("
                       + _mm(_type(entity)) + ')"]')
        for child in graph.children_of(key):
            mermaid.append("  " + nid(key) + " --> " + nid(child))
            walk(child, depth + 1)

    roots = _roots(graph)
    for root in roots:
        walk(root, 0)
    mermaid.append("```")

    counts = {}
    for entity in graph.entities.values():
        counts[_type(entity)] = counts.get(_type(entity), 0) + 1
    breakdown = ", ".join(t + ": " + str(n) for t, n in sorted(counts.items()))

    body = [
        _front_matter(
            "Geography -- Containment Tree (generated)",
            "Generated containment outline of the geography entity tree (the "
            "folder / parent walk): city, districts, buildings, rooms, objects."),
        _banner_body("The containment tree of every place."),
        "# Containment Tree (generated)\n",
        str(len(graph.entities)) + " entities. By type -- " + breakdown + ".\n",
        "## Outline\n",
        ("\n".join(outline) if outline else "_The tree is empty._"),
        "",
        "## Diagram\n",
        "\n".join(mermaid),
        "",
    ]
    return "\n".join(body) + "\n"


# ---------------------------------------------------------------------------
# View 3: what's on each street.
# ---------------------------------------------------------------------------


def build_street_index(graph):
    streets = sorted(graph.streets(), key=lambda e: e.key)
    sections = []

    for street in streets:
        sections.append("## " + _safe(_label(street)) + "  (`"
                        + _safe(street.entity_id) + "`)\n")

        segs = graph.segments_of_street(street.key)
        sections.append("**Segments (" + str(len(segs)) + "):**")
        if segs:
            for seg_key in segs:
                seg = graph.entities[seg_key]
                length = (" -- " + str(seg.length_m) + " m") if isinstance(
                    seg.length_m, (int, float)) else ""
                sections.append("- `" + _safe(seg.entity_id) + "`" + _safe(length))
        else:
            sections.append("- _none recorded_")

        inters = _connected_intersections(graph, street.key)
        sections.append("\n**Intersections (" + str(len(inters)) + "):**")
        if inters:
            for inter_key in inters:
                inter = graph.entities[inter_key]
                sections.append("- `" + _safe(inter.entity_id) + "` -- "
                                + _safe(_label(inter)))
        else:
            sections.append("- _none recorded_")

        addresses = graph.whats_on_street(street.key)
        sections.append("\n**Addresses on this street (" + str(len(addresses))
                        + "):**")
        if addresses:
            for addr_key in addresses:
                addr = graph.entities[addr_key]
                sections.append("- `" + _safe(addr.entity_id) + "` -- "
                                + _safe(_label(addr)))
        else:
            sections.append("- _none recorded_")
        sections.append("")

    body = [
        _front_matter(
            "Geography -- What's On Each Street (generated)",
            "Generated index of what sits on each street: its segments, the "
            "intersections it meets, and the addresses that reference it."),
        _banner_body("What sits on each street."),
        "# What's On Each Street (generated)\n",
        str(len(streets)) + " named street(s) in canon.\n",
        ("\n".join(sections) if sections
         else "_No streets recorded yet._"),
        "",
    ]
    return "\n".join(body) + "\n"


# ---------------------------------------------------------------------------
# Driver.
# ---------------------------------------------------------------------------


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    geography_dir = argv[0] if argv else eg.GEOGRAPHY_DIR

    graph = eg.build_graph(geography_dir)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    artifacts = {
        "street-network.md": build_street_network(graph),
        "containment-tree.md": build_containment_tree(graph),
        "street-index.md": build_street_index(graph),
    }

    print("Geography view generator for The Unnecessary")
    print("Source tree: " + geography_dir)
    print("Entities walked: " + str(len(graph.entities))
          + " (externals resolved: " + str(len(graph.externals)) + ")")
    print("Output dir: " + OUTPUT_DIR)
    print("")
    for name, content in artifacts.items():
        path = os.path.join(OUTPUT_DIR, name)
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(content)
        print("  wrote " + os.path.relpath(path, eg.REPO_ROOT)
              + "  (" + str(len(content.splitlines())) + " lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
